### ISSUE TITLE
Make error on linux mint 21.1 cinnamon

### ISSUE THREAD

**Issue by rusbomber** [Scribery/cockpit-session-recording#134]
make
NODE_ENV= ./build.js
file:///home/admini/git/cockpit-session-recording/build.js:18
const esbuild = (await import(useWasm ? 'esbuild-wasm' : 'esbuild')).default;
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
make: *** [Makefile:85: dist/manifest.json] Error 1

**Comment by justin-stephenson** [comment]
Hi, 

What version of Node JS is installed on your system?

**Comment by rusbomber** [comment]
10.24.0

**Comment by justin-stephenson** [comment]
It seems the `import` declaration is supported in Node JS 13.2.0 and higher. You could try building with the v12 release. A majority of the changes in the latest release are build related changes, no new functionality in the module itself.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
