### ISSUE TITLE
cockpit session recording centos 7.8 , when i click on browser to run recording it shows this error and crash 

### ISSUE THREAD

**Issue by masadrasheed** [Scribery/cockpit-session-recording#65]
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Player (created by Recording)
    in div (created by Recording)
    in div (created by Recording)
    in Recording (created by View)
warningWithoutStack @ react-dom.development.js:512
react-dom.development.js:62 Uncaught Invariant Violation: Objects are not valid as a React child (found: Error: extra output present). If you meant to render a collection of children, use an array instead.
    in div (created by Player)
    in div (created by Player)
    in div (created by Player)
    in div (created by Player)
    in Player (created by Recording)
    in div (created by Recording)
    in div (created by Recording)
    in Recording (created by View)
    in View
    at invariant (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:42214:15)
    at throwOnInvalidObjectType (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:54383:5)
    at createChild (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:54594:7)
    at reconcileChildrenArray (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:54826:25)
    at reconcileChildFibers (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:55149:14)
    at reconcileChildren (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:55542:28)
    at updateHostComponent (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:55821:3)
    at beginWork (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:56263:14)
    at performUnitOfWork (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:58575:12)
    at workLoop (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:58613:24)
react-dom.development.js:14550 The above error occurred in the <div> component:
    in div (created by Player)
    in div (created by Player)
    in div (created by Player)
    in div (created by Player)
    in Player (created by Recording)
    in div (created by Recording)
    in div (created by Recording)
    in Recording (created by View)
    in View

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:14550
react-dom.development.js:17356 Uncaught Invariant Violation: Objects are not valid as a React child (found: Error: extra output present). If you meant to render a collection of children, use an array instead.
    in div (created by Player)
    in div (created by Player)
    in div (created by Player)
    in div (created by Player)
    in Player (created by Recording)
    in div (created by Recording)
    in div (created by Recording)
    in Recording (created by View)
    in View
    at invariant (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:42214:15)
    at throwOnInvalidObjectType (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:54383:5)
    at createChild (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:54594:7)
    at reconcileChildrenArray (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:54826:25)
    at reconcileChildFibers (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:55149:14)
    at reconcileChildren (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:55542:28)
    at updateHostComponent (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:55821:3)
    at beginWork (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:56263:14)
    at performUnitOfWork (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:58575:12)
    at workLoop (https://test.test.com/webcon/cockpit+=v6testdevops/$3f24e3f6f148a9f3fab89f33e8828675297501b7475c8172a89cd95873e03dc0/session-recording/recordings.js:58613:24)
6player.jsx:659 Error: extra output present
    at PacketBuffer.parseMessageData (player.jsx:354)
    at PacketBuffer.parseMessage (player.jsx:403)
    at PacketBuffer.handleStream (player.jsx:436)
    at fire_streamers (journal.js:145)
handleError @ player.jsx:659
react-dom.development.js:512 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in View
warningWithoutStack @ react-dom.development.js:512
146player.test.test.com

**Comment by justin-stephenson** [comment]
Thank you for the report @masadrasheed 

Does this happen for you with all recordings or just one? Could you provide some steps to reproduce this issue on my end? Based on the error `extra output present` it might be a problem with only a specific tlog recording.

**Comment by masadrasheed** [comment]
yes you are right its just related to specific Tlog recording but after that it  stop showing more Tlog recording and start behaving strange in cockpit.

I think it happen after I try to access terminal via cockpit and suddenly this happen , I think if I delete that Tlog recording (which I don't know how to) may be it start working properly  (please let me know command to delete that particular recording as I already know id)

**Comment by justin-stephenson** [comment]
@masadrasheed The recordings are read from the systemd journal. The systemd journal API does not allow removing specific recordings, you would need to clear out the journal entries with the journalctl command but you will lose other recordings if they exist in the journal from a similar timeframe.

https://unix.stackexchange.com/questions/139513/how-to-clear-journalctl

It would be great if you can post the output of
```
  $ journalctl TLOG_REC=$recid
```
where $recid is the recording id(you will see this in the URL of the Player page: `localhost:9090/session-recording#/recid`

**Comment by masadrasheed** [comment]
I think that recid is deleted , last time I play this it show me some data which keep running on screen instead of recording.

Now I have an other issue , I set 


usermod -s /usr/bin/tlog-rec-session asad

[root@V6TestDevops devops]# su asad

ATTENTION! Your session is being recorded!

(Note it stuck here , no bash)

############################################################
But if I run directly from shell its start recording 


[root@V6TestDevops devops]# /usr/bin/tlog-rec-session

ATTENTION! Your session is being recorded!

[root@V6TestDevops devops]# 

after I fix the above issue I think I can reproduce the issue because I think it come only when I open terminal from cockpit and also same user (which on cockpit termial) on  ssh directly tlog get crash.

**Comment by justin-stephenson** [comment]
@masadrasheed what does the output of `tlog-rec-session --configuration` show? The 'shell' should be **/bin/bash**, or some other shell that can be started by tlog-rec-session.

Do you have a 'tlog' user added to the system? and the correct permissions of `/usr/bin/tlog-rec-session`
~~~
$ id tlog
uid=973(tlog) gid=971(tlog) groups=971(tlog)

$ ls -l $(which tlog-rec-session)
-rwsr-sr-x. 1 tlog tlog 16456 Jan 30  2020 /usr/bin/tlog-rec-session
~~~

How was tlog installed in your environment?

**Comment by masadrasheed** [comment]
[devops@V6TestDevops ~]$ tlog-rec-session --configuration
{
  "notice":"\nATTENTION! Your session is being recorded!\n\n",
  "latency":10,
  "payload":2048,
  "log":{
    "input":true,
    "output":true,
    "window":true
  },
  "limit":{
    "rate":16384,
    "burst":32768,
    "action":"pass"
  },
  "file":{
    "path":""
  },
  "syslog":{
    "facility":"authpriv",
    "priority":"info"
  },
  "journal":{
    "priority":"info",
    "augment":true
  },
  "writer":"journal",
  "shell":"\/bin\/bash",
  "configuration":true,
  "args":[
  ]
}


[devops@V6TestDevops ~]$ id tlog
uid=996(tlog) gid=992(tlog) groups=992(tlog)
[devops@V6TestDevops ~]$ 


[devops@V6TestDevops ~]$ ls -l $(which tlog-rec-session)
-rwsr-sr-x 1 tlog tlog 11336 May 29  2019 /usr/bin/tlog-rec-session
[devops@V6TestDevops ~]$ 

I installed via rpm 

wget -c https://dl.fedoraproject.org/pub/epel/testing/7/x86_64/Packages/t/tlog-6-1.el7.x86_64.rpm
yum install tlog-6-1.el7.x86_64.rpm 

https://copr.fedorainfracloud.org/coprs/ableisch/cockpit-session-recording/packages/

for cockpit session recording I am using above package.

Last thing as I mention before if run command on shell  /usr/bin/tlog-rec-session (session recoding start working)

but if I change shell to /usr/bin/tlog-rec-session permanently it stuck.

**Comment by justin-stephenson** [comment]
Thanks, let me do a quick test on CentOS7 and see if I can reproduce the problem.

**Comment by masadrasheed** [comment]
ok great :) , looking forward

**Comment by justin-stephenson** [comment]
@masadrasheed I installed a fresh CentOS 7.8 VM, installed tlog and created a new user, but I don't see any issues on my end.
```
[root@localhost ~]# usermod -s /usr/bin/tlog-rec-session recuser
[root@localhost ~]# su recuser

ATTENTION! Your session is being recorded!

[recuser@localhost root]$ echo $SHELL
/bin/bash
[recuser@localhost root]$ exit
```
~~~
$ _getent_ passwd recuser
recuser:x:1000:1000::/home/recuser:/usr/bin/tlog-rec-session
~~~

Do you see any error in the journal?

Does strace give you any clues what is failing?

**Comment by masadrasheed** [comment]
First I don't know what terminal issue is so I setup new machine , lets skip that issue.

I reproduce the issue now

**Comment by masadrasheed** [comment]
issue start when you run the terminal from cockpit

**Comment by masadrasheed** [comment]
I hope you understand that if terminal run from cockpit its recording get corrupted can cannot be played but if you ssh then you see all recordings on cockpit session recording and can be played easily without any error.

**Comment by justin-stephenson** [comment]
@masadrasheed `tlog` is designed to record Terminal I/O only and therefore is unable to record activity of graphical, or cockpit sessions because the recording can be easily circumvented/avoided in these scenarios(modifying configurations in the Accounts, or Services cockpit pages cannot be recorded for example). That is why tlog is only intended for activity in the terminal, over SSH, or on the console.

If you want to record cockpit session activity, you would need to use some graphical tool for that.

**Comment by masadrasheed** [comment]
> @masadrasheed `tlog` is designed to record Terminal I/O only and therefore is unable to record activity of graphical, or cockpit sessions because the recording can be easily circumvented/avoided in these scenarios(modifying configurations in the Accounts, or Services cockpit pages cannot be recorded for example). That is why tlog is only intended for activity in the terminal, over SSH, or on the console.
> 
> If you want to record cockpit session activity, you would need to use some graphical tool for that.

I only want to record terminal activity (but terminal access from cockpit web console, screenshot attached) not cockpit session , please correct me if I am wrong if it supported or not as it log session recordings but crashing.


<img width="1440" alt="Screenshot 2020-10-14 at 4 19 34 PM" src="https://user-images.githubusercontent.com/20185686/95994621-30d32200-0e39-11eb-8a50-3b2ec17800b2.png">

**Comment by justin-stephenson** [comment]
Sorry @masadrasheed this is not a supported use case, cockpit exec's the tlog-rec-session shell which starts cockpit-bridge underneath allowing login to the cockpit UI, but `cockpit-bridge` is not the same as a normal login session on the terminal and thus does not recording terminal I/O as you might expect.

**Comment by masadrasheed** [comment]
Thank you man , I really appreciate your support.

BTW I fix the issue.





---- On Wed, 14 Oct 2020 18:47:40 +0500 Justin Stephenson <notifications@github.com> wrote ----




Sorry https://github.com/masadrasheed this is not a supported use case, cockpit exec's the tlog-rec-session shell which starts cockpit-bridge underneath allowing login to the cockpit UI, but cockpit-bridge is not the same as a normal login session on the terminal and thus does not recording terminal I/O as you might expect.
